version: "3.9"
name: wireguard

services:
  server:
    build:
      context: ${PWD}
      dockerfile: Dockerfile
      tags:
        - infra7/wireguard:${WIREGUARD_RELEASE:-latest}
    image: infra7/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      PUID: 1000
      PGID: 1000
      TZ: ${TZ:-Etc/UTC}
      SERVERURL: auto
      SERVERPORT: ${SERVERPORT:-51820}
      PERSISTENTKEEPALIVE_PEERS: all
      LOG_CONFS: true
    networks:
      wireguard:
    ports:
      - ${SERVERPORT:-51820}:${SERVERPORT:-51820}/udp
    restart: unless-stopped
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    volumes:
      - ${PWD}/config:/config
      - /lib/modules:/lib/modules

networks:
  wireguard:
    name: wireguard
